# Generated by Django 4.2.16 on 2024-10-04 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('location', models.CharField(max_length=100, verbose_name='location')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('phone_number', models.CharField(max_length=20, verbose_name='phone number')),
                ('hire_date', models.DateField(verbose_name='hire date')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='salary')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_users.department')),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='employees',
            field=models.ManyToManyField(related_name='employee_name', to='app_users.employee'),
        ),
    ]
