# Generated by Django 4.2.16 on 2024-10-04 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0002_alter_employee_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='employees',
            field=models.ManyToManyField(blank=True, null=True, related_name='employee_name', to='app_users.employee'),
        ),
    ]
